#!/bin/bash

cleanup() {
    displayMsg ""
    displayMsg OK "Creating backup of the system ..."
    sudo cp -ru "${MOUNT_POINT}${TOOLS_DIR}" "${MOUNT_POINT}${BACKUP_DIR}"
    displayMsg OK "Done ..."
    
    displayMsg ""
    displayMsg OK "Cleaning up the mess ..."
#    rm -rf "${MOUNT_POINT}${BUILD_DIR}"
#    sudo rm -rf "${MOUNT_POINT}${TOOLS_DIR}"
    sudo rm -rf /tools
    
    # Unmount the filesystem
    sudo umount -l $PARTITION
    displayMsg OK "Done ..."
}

cleanupBuild() {
    displayMsg ""
    displayMsg OK "Cleaning up the mess ..."
    cd "${MOUNT_POINT}${BUILD_DIR}"
    sudo rm -R -- */
    cd ../../
    cd ${MOUNT_POINT}${PKG_BASIC_DIR}
    sudo rm -R -- */
    cd ../../
    displayMsg OK "Done ..."
}