#!/bin/bash

# Begins setup
initSetup() {
    displayMsg ""
    displayMsg OK "Starting Installation ..."

    # Pass 1
    BUILD binutils BASIC
    BUILD gcc BASIC
    BUILD linux-api-headers BASIC
    BUILD glibc BASIC
    BUILD libstdc++ BASIC
    
    # Clean up extracted pakages
    cleanupBuild
    
    # Pass 2
    BUILD binutils BASIC
    BUILD gcc BASIC
    
    # Clean up extracted pakages
    cleanupBuild
    
    # Test Suites
    BUILD tcl BASIC
    BUILD expect BASIC
    BUILD dejagnu BASIC
    BUILD check BASIC
    
    # Clean up extracted pakages
    cleanupBuild
    
    # Prepare rest of the system
    BUILD ncurses BASIC
    BUILD bash BASIC
    BUILD bzip BASIC
    BUILD coreutils BASIC
    BUILD diffutils BASIC
    BUILD file BASIC
    BUILD findutils BASIC
    BUILD gwak BASIC
    
    # Clean up extracted pakages
    cleanupBuild
}