#!/bin/bash

FOLDERNAME="bash-4.3.30"
FILENAME="bash-4.3.30.tar.gz"

# The Bash package contains the Bourne-Again SHell.

cd ../../pkg/basic/${FOLDERNAME}

# Prepare Bash for compilation
./configure --prefix=/tools \
            --without-bash-malloc
            
# Compile the package
make $MAKEFLAGS

# Install the package
make $MAKEFLAGS install

# Make a link for the programs that use sh for a shell
ln -s bash /tools/bin/sh