#!/bin/bash

FOLDERNAME="binutils-2.25.1"
FILENAME="binutils-2.25.1.tar.bz2"

CC=$TARGET-gcc                      \
AR=$TARGET-ar                       \
RANLIB=$TARGET-ranlib               \
../../pkg/${FOLDERNAME}/configure   \
    --prefix=/tools                 \
    --disable-nls                   \
    --disable-werror                \
    --with-lib-path=/tools/lib      \
    --with-sysroot

make $MAKEFLAGS && make $MAKEFLAGS install

make $MAKEFLAGS -C ld clean
make $MAKEFLAGS -C ld LIB_PATH=/usr/lib:/lib
cp -v ld/ld-new /tools/bin