#!/bin/bash

FOLDERNAME="bzip2-1.0.6"
FILENAME="bzip2-1.0.6.tar.gz"

# The Bzip2 package contains programs for compressing
# and decompressing files. Compressing text files with
# bzip2 yields a much better compression percentage than
# with the traditional gzip.

cd ../../pkg/basic/${FOLDERNAME}
            
# Compile the package
make $MAKEFLAGS

# Install the package
make $MAKEFLAGS PREFIX=/tools install