#!/bin/bash

FOLDERNAME="bzip2-1.0.6"
FILENAME="bzip2-1.0.6.tar.gz"

# Prepare Bash for compilation
cp -rv ../../pkg/${FOLDERNAME}/* ./

# Build the package
make $MAKEFLAGS

# Install the package
make $MAKEFLAGS PREFIX=/tools install