#!/bin/bash

FOLDERNAME="attr-2.4.47"
FILENAME="attr-2.4.47.src.tar.gz"

# The attr package contains utilities to administer
# the extended attributes on filesystem objects.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Modify the documentation directory so that it
# is a versioned directory
sed -i -e 's|/@pkg_name@|&-@pkg_version@|' include/builddefs.in

# Prevent installation of manual pages that
# were already installed by the man pages package
sed -i -e "/SUBDIRS/s|man2||" man/Makefile

# Prepare Attr for compilation
./configure --prefix=/usr           \
            --disable-static

# Compile the package
make

# Install the package
make install install-dev install-lib
chmod -v 755 /usr/lib/libattr.so

# The shared library needs to be moved to /lib,
# and as a result the .so file in /usr/lib will
# need to be recreated
mv -v /usr/lib/libattr.so.* /lib
ln -sfv ../../../lib/$(readlink /usr/lib/libattr.so) /usr/lib/libattr.so