#!/bin/bash

FOLDERNAME="acl-2.2.52"
FILENAME="acl-2.2.52.src.tar.gz"

# The Acl package contains utilities to administer
# Access Control Lists, which are used to define
# more fine-grained discretionary access rights
# for files and directories.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Modify the documentation directory so that it
# is a versioned directory
sed -i -e 's|/@pkg_name@|&-@pkg_version@|' include/builddefs.in

# Fix some broken tests
sed -i "s:| sed.*::g" test/{sbits-restore,cp,misc}.test

# Fix a bug that causes getfacl -e to segfault
# on overly long group name
sed -i -e "/TABS-1;/a if (x > (TABS-1)) x = (TABS-1);" \
    libacl/__acl_to_any_text.c

# Prepare Acl for compilation
./configure --prefix=/usr    \
            --disable-static \
            --libexecdir=/usr/lib

# Compile the package
make

# Install the package
make install install-dev install-lib
chmod -v 755 /usr/lib/libacl.so

# The shared library needs to be moved to /lib,
# and as a result the .so file in /usr/lib will
# need to be recreated
mv -v /usr/lib/libacl.so.* /lib
ln -sfv ../../../../lib/$(readlink /usr/lib/libacl.so) /usr/lib/libacl.so