#!/bin/bash

FOLDERNAME="bzip2-1.0.6"
FILENAME="bzip2-1.0.6.tar.gz"

# The Bzip2 package contains programs for compressing and
# decompressing files. Compressing text files with bzip2
# yields a much better compression percentage than with
# the traditional gzip.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}
    
# Apply a patch that will install the documentation for
# this package
patch -Np1 -i ../bzip2-1.0.6-install_docs-1.patch

# Ensure installation of symbolic links are relative
sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile

# Ensure the man pages are installed into the correct
# location
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile

# Prepare Bzip2 for compilation
make -f Makefile-libbz2_so
make clean

# Compile the package
make

# Install the programs
make PREFIX=/usr install

# Install the shared bzip2 binary into the /bin
# directory, make some necessary symbolic links,
# and clean up
cp -v bzip2-shared /bin/bzip2
cp -av libbz2.so* /lib
ln -sv ../../../tools/lib/libbz2.so.1.0 /usr/lib/libbz2.so
rm -v /usr/bin/{bunzip2,bzcat,bzip2}
ln -sv bzip2 /bin/bunzip2
ln -sv bzip2 /bin/bzcat
