#!/bin/bash

FOLDERNAME="file-5.24"
FILENAME="file-5.24.tar.gz"

# The File package contains a utility for determining
# the type of a given file or files.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}
    
# Prepare File for compilation
./configure --prefix=/usr

# Compile the package
make

# Install the package
make install