#!/bin/bash

FOLDERNAME="findutils-4.4.2"
FILENAME="findutils-4.4.2.tar.gz"

# The Findutils package contains programs to find files.
# These programs are provided to recursively search through
# a directory tree and to create, maintain, and search a
# database (often faster than the recursive find, but
# unreliable if the database has not been recently updated).
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Prepare Findutils for compilation
./configure --prefix=/usr \
            --localstatedir=/var/lib/locate

# Compile the package
make

# Install the package
make install

# Some packages expect the find program in /bin
mv -v /usr/bin/find /bin
sed -i 's|find:=${BINDIR}|find:=/bin|' /usr/bin/updatedb