#!/bin/bash

FOLDERNAME="glibc-2.22"
FILENAME="glibc-2.22.tar.xz"

# The Glibc package contains the main C library. This
# library provides the basic routines for allocating
# memory, searching directories, opening and closing
# files, reading and writing files, string handling,
# pattern matching, arithmetic, and so on.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}
# Apply the following patch to make programs store their
# runtime data in the FHS-compliant locations
patch -Np1 -i ../glibc-2.22-fhs-1.patch
# Fix a build problem that affects i386 systems
patch -Np1 -i ../glibc-2.22-upstream_i386_fix-1.patch

# Change directory to the build folder
cd /src/build/ch-glibc

# Prepare Glibc for compilation
../../pkg/basic/${FOLDERNAME}/configure    \
    --prefix=/usr          \
    --disable-profile      \
    --enable-kernel=2.6.32 \
    --enable-obsolete-rpc

# Compile the package
make

# Though it is a harmless message, the install stage
# of Glibc will complain about the absence of
#/etc/ld.so.conf. Prevent this warning
touch /etc/ld.so.conf

# Install the package
make install

# Install the configuration file and runtime
# directory for nscd
cp -v /src/pkg/basic/${FOLDERNAME}/nscd/nscd.conf /etc/nscd.conf
mkdir -pv /var/cache/nscd

# Install the minimum set of locales
mkdir -pv /usr/lib/locale
localedef -i cs_CZ -f UTF-8 cs_CZ.UTF-8
localedef -i de_DE -f ISO-8859-1 de_DE
localedef -i de_DE@euro -f ISO-8859-15 de_DE@euro
localedef -i de_DE -f UTF-8 de_DE.UTF-8
localedef -i en_GB -f UTF-8 en_GB.UTF-8
localedef -i en_HK -f ISO-8859-1 en_HK
localedef -i en_PH -f ISO-8859-1 en_PH
localedef -i en_US -f ISO-8859-1 en_US
localedef -i en_US -f UTF-8 en_US.UTF-8
localedef -i es_MX -f ISO-8859-1 es_MX
localedef -i fa_IR -f UTF-8 fa_IR
localedef -i fr_FR -f ISO-8859-1 fr_FR
localedef -i fr_FR@euro -f ISO-8859-15 fr_FR@euro
localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
localedef -i it_IT -f ISO-8859-1 it_IT
localedef -i it_IT -f UTF-8 it_IT.UTF-8
localedef -i ja_JP -f EUC-JP ja_JP
localedef -i ru_RU -f KOI8-R ru_RU.KOI8-R
localedef -i ru_RU -f UTF-8 ru_RU.UTF-8
localedef -i tr_TR -f UTF-8 tr_TR.UTF-8
localedef -i zh_CN -f GB18030 zh_CN.GB18030

# Install all locales listed in the
# glibc-2.22/localedata/SUPPORTED file
make localedata/install-locales

    
# Install Man-pages
make install

###################
# CONFIGURE GLIBC #
###################

# The /etc/nsswitch.conf file needs to be created because the
# Glibc defaults do not work well in a networked environment.
cat > /etc/nsswitch.conf << "EOF"
# Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

hosts: files dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
EOF

# Install and set up the timezone data
tar -xf /src/pkg/basic/tzdata2015f.tar.gz

ZONEINFO=/usr/share/zoneinfo
mkdir -pv $ZONEINFO/{posix,right}

for tz in etcetera southamerica northamerica europe africa antarctica  \
          asia australasia backward pacificnew systemv; do
    zic -L /dev/null   -d $ZONEINFO       -y "sh yearistype.sh" ${tz}
    zic -L /dev/null   -d $ZONEINFO/posix -y "sh yearistype.sh" ${tz}
    zic -L leapseconds -d $ZONEINFO/right -y "sh yearistype.sh" ${tz}
done

cp zone.tab zone1970.tab iso3166.tab $ZONEINFO
zic -d $ZONEINFO -p America/New_York
unset ZONEINFO

# Create the /etc/localtime file
cp /usr/share/zoneinfo/America/New_York /etc/localtime

# By default, the dynamic loader (/lib/ld-linux.so.2) searches
# through /lib and /usr/lib for dynamic libraries that are
# needed by programs as they are run. However, if there are
# libraries in directories other than /lib and /usr/lib, these
# need to be added to the /etc/ld.so.conf file in order for
# the dynamic loader to find them. Two directories that are
# commonly known to contain additional libraries are /usr/local/lib
# and /opt/lib, so add those directories to the dynamic loader's
# search path. 
# Create a new file /etc/ld.so.conf
cat > /etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf
/usr/local/lib
/opt/lib

EOF

# If desired, the dynamic loader can also search a directory and
# include the contents of files found there. Generally the files
# in this include directory are one line specifying the desired
# library path.
cat >> /etc/ld.so.conf << "EOF"
# Add an include directory
include /etc/ld.so.conf.d/*.conf

EOF
mkdir -p /etc/ld.so.conf.d