#!/bin/bash

FOLDERNAME="gdbm-1.11"
FILENAME="gdbm-1.11.tar.gz"

# The GDBM package contains the GNU Database Manager. It is a
# library of database functions that use extensible hashing
# and work similar to the standard UNIX dbm. The library
# provides primitives for storing key/data pairs, searching
# and retrieving the data by its key and deleting a key along
# with its data.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Prepare GDBM for compilation
./configure --prefix=/usr \
            --disable-static \
            --enable-libgdbm-compat

# Compile the package
make

# Install the package
make install