#!/bin/bash

FOLDERNAME="gawk-4.1.3"
FILENAME="gawk-4.1.3.tar.xz"

# The Gawk package contains programs for manipulating text files.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Prepare Gawk for compilation
./configure --prefix=/usr

# Compile the package
make

# Install the package
make install

# Install the documentation
mkdir -v /usr/share/doc/gawk-4.1.3
cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-4.1.3