#!/bin/bash

FOLDERNAME="gcc-5.2.0"
FILENAME="gcc-5.2.0.tar.bz2"

# The GCC package contains the GNU compiler collection, which
# includes the C and C++ compilers.
    
# Change directory
cd /src/build/ch-gcc

# Prepare GCC for compilation
SED=sed                                 \
../../pkg/basic/${FOLDERNAME}/configure \
     --prefix=/usr                      \
     --enable-languages=c,c++           \
     --disable-multilib                 \
     --disable-bootstrap                \
     --with-system-zlib

# Compile the package
make

# Install the package
make install

# Some packages expect the C preprocessor to be installed
# in the /lib directory.
ln -s ../../../usr/bin/cpp /lib

# Many packages use the name cc to call the C compiler.
ln -s gcc /usr/bin/cc

# Add a compatibility symlink to enable building
# programs with Link Time Optimization (LTO)
install -dm755 /usr/lib/bfd-plugins
ln -sf ../../../tools/libexec/gcc/$(gcc -dumpmachine)/5.2.0/liblto_plugin.so /usr/lib/bfd-plugins/