#!/bin/bash

FOLDERNAME="linux-4.2"
FILENAME="linux-4.2.tar.xz"

# The Linux package contains the Linux kernel.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}
    
# Make sure there are no stale files embedded in the package
make mrproper

# Set the base configuration to a good state that takes your
# current system architecture into account
make defconfig

# Compile the kernel image and modules
make
# Install the modules
make modules_install

# The path to the kernel image may vary depending on the platform being
# used. The filename below can be changed to suit your taste, but the
# stem of the filename should be vmlinuz to be compatible with the
# automatic setup of the boot process
cp -v arch/x86/boot/bzImage /boot/vmlinuz-0.3-panda-linux

# System.map is a symbol file for the kernel. It maps the function entry
# points of every function in the kernel API, as well as the addresses of
# the kernel data structures for the running kernel. It is used as a
# resource when investigating kernel problems. Issue the following command
# to install the map file
cp -v System.map /boot/System.map-0.1

# Install the documentation for the Linux kernel
install -d /usr/share/doc/linux-4.2
cp -r Documentation/* /usr/share/doc/linux-4.2

#######################################
# Configuring Linux Module Load Order #
#######################################

# Create a new file /etc/modprobe.d/usb.conf
install -v -m755 -d /etc/modprobe.d
cat > /etc/modprobe.d/usb.conf << "EOF"
# Begin /etc/modprobe.d/usb.conf

install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true

# End /etc/modprobe.d/usb.conf
EOF

###########################
# GRUB configuration file #
###########################

# Generate /boot/grub/grub.cfg
mkdir -v /boot/grub
cat > /boot/grub/grub.cfg << "EOF"
# Begin /boot/grub/grub.cfg
set default=0
set timeout=10

insmod ext4
set root=(hd0,10)

menuentry "Panda Linux" {
        linux   /boot/vmlinuz-0.3-panda-linux root=/dev/sda10 ro
}
EOF

###############
# Final Touch #
###############

# Create an /etc/os-release file required by systemd
cat > /etc/os-release << "EOF"
NAME="Panda Linux"
VERSION="0.3"
ID=panda
PRETTY_NAME="Panda Linux v0.3"
EOF

# Create /etc/lfs-release for compatibility with non systemd branch
echo 0.3a > /etc/panda-release

# Create a file to show the status of your new system with respect
# to the Linux Standards Base (LSB)
cat > /etc/lsb-release << "EOF"
DISTRIB_ID="Panda Linux"
DISTRIB_RELEASE="v0.3a"
DISTRIB_CODENAME="panda"
DISTRIB_DESCRIPTION="Panda Linux"
EOF