#!/bin/bash

FOLDERNAME="linux-4.2"
FILENAME="linux-4.2.tar.xz"

# The Linux kernel needs to expose an Application Programming Interface
# (API) for the system's C library (Glibc in LFS) to use. This is done
# by way of sanitizing various C header files that are shipped in the
# Linux kernel source tarball.
displayMsg OK "Building Pass 2 ..."
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}
    
# Make sure there are no stale files embedded in the package
make mrproper
    
# Extract the user-visible kernel headers from the source.
# They are placed in an intermediate local directory and
# copied to the needed location because the extraction process
# removes any existing files in the target directory.
make INSTALL_HDR_PATH=dest headers_install
find dest/include \( -name .install -o -name ..install.cmd \) -delete
cp -r dest/include/* /usr/include