#!/bin/bash

FOLDERNAME="mpfr-3.1.3"
FILENAME="mpfr-3.1.3.tar.xz"

# The MPFR package contains functions for multiple precision math.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Apply the following patch to fix various bugs
patch -Np1 -i ../mpfr-3.1.3-upstream_fixes-1.patch

# Prepare MPFR for compilation
./configure --prefix=/usr    \
            --disable-static \
            --enable-thread-safe \
            --docdir=/usr/share/doc/mpfr-3.1.3

# Compile the package
make
# Generate the HTML Documentation
make html

# Install the package
make install
# Install the Documentation
make install-html