#!/bin/bash

FOLDERNAME="m4-1.4.17"
FILENAME="m4-1.4.17.tar.xz"

# The M4 package contains a macro processor.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Prepare M4 for compilation
./configure --prefix=/usr

# Compile the package
make

# Install the package
make install