#!/bin/bash

FOLDERNAME="perl-5.22.0"
FILENAME="perl-5.22.0.tar.xz"

# The Perl package contains the Practical Extraction
# and Report Language.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Create a basic /etc/hosts file to be referenced
# in one of Perl's configuration files
echo "127.0.0.1 localhost $(hostname)" > /etc/hosts

# This version of Perl now builds the
# Compress::Raw::Zlib and Compress::Raw::BZip2 modules.
# By default Perl will use an internal copy of the sources
# for the build. Issue the following command so that Perl
# will use the libraries installed on the system
export BUILD_ZLIB=False
export BUILD_BZIP2=0

# Prepare Perl for compilation
sh Configure -des -Dprefix=/usr                 \
                  -Dvendorprefix=/usr           \
                  -Dman1dir=/usr/share/man/man1 \
                  -Dman3dir=/usr/share/man/man3 \
                  -Dpager="/usr/bin/less -isR"  \
                  -Duseshrplib

# Compile the package
make

# Install the package
make install
unset BUILD_ZLIB BUILD_BZIP2