#!/bin/bash

FOLDERNAME="patch-2.7.5"
FILENAME="patch-2.7.5.tar.xz"

# The Patch package contains a program for modifying or creating
# files by applying a “patch” file typically created by the diff
# program.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Prepare Patch for compilation
./configure --prefix=/usr

# Compile the package
make

# Install the package
make install