#!/bin/bash

FOLDERNAME="readline-6.3"
FILENAME="readline-6.3.tar.gz"

# The Readline package is a set of libraries that offers
# command-line editing and history capabilities.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Install some patches to fix various bugs
patch -Np1 -i ../readline-6.3-upstream_fixes-3.patch

# Reinstalling Readline will cause the old libraries to
# be moved to <libraryname>.old. While this is normally
# not a problem, in some cases it can trigger a linking
# bug in ldconfig. This can be avoided by issuing the
# following two seds
sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install

# Prepare Readline for compilation
./configure --prefix=/usr \
            --disable-static \
            --docdir=/usr/share/doc/readline-6.3

# Compile the package
make SHLIB_LIBS=-lncurses

# Install the package
make SHLIB_LIBS=-lncurses install

# Move the dynamic libraries to a more appropriate
# location and fix up some symbolic links
mv -v /usr/lib/lib{readline,history}.so.* /lib
ln -sfv ../../../lib/$(readlink /usr/lib/libreadline.so) /usr/lib/libreadline.so
ln -sfv ../../../lib/$(readlink /usr/lib/libhistory.so ) /usr/lib/libhistory.so

# Install the documentation
install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-6.3