#!/bin/bash

FOLDERNAME="shadow-4.2.1"
FILENAME="shadow-4.2.1.tar.xz"

# The Shadow package contains programs for handling
# passwords in a secure way.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Disable the installation of the groups program and
# its man pages, as Coreutils provides a better version
sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /' {} \;

# Instead of using the default crypt method, use the
# more secure SHA-512 method of password encryption,
# which also allows passwords longer than 8 characters.
# It is also necessary to change the obsolete /var/spool/mail
# location for user mailboxes that Shadow uses by default to
# the /var/mail location used currently
sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs
       
# Make a minor change to make the default useradd
# consistent with the LFS groups file
sed -i 's/1000/999/' etc/useradd

# Prepare Shadow for compilation
./configure --sysconfdir=/etc \
            --with-group-name-max-length=32

# Compile the package
make

# Install the package
make install

# Move a misplaced program to its proper location
mv -v /usr/bin/passwd /bin

####################
# Configure Shadow #
####################

# Enable shadowed passwords
pwconv
# Enable shadowed group passwords
grpconv

# Choose a password for user root and set it
passwd root