#!/bin/bash

FOLDERNAME="texinfo-6.0"
FILENAME="texinfo-6.0.tar.xz"

# The Texinfo package contains programs for reading, writing,
# and converting info pages.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Prepare Texinfo for compilation:
./configure --prefix=/usr
            
# Compile the package
make

# Install the package
make install
# Optionally, install the components belonging in a
# TeX installation
make TEXMF=/usr/share/texmf install-tex

# The Info documentation system uses a plain text file to
# hold its list of menu entries. The file is located at
# /usr/share/info/dir. Unfortunately, due to occasional
# problems in the Makefiles of various packages, it can
# sometimes get out of sync with the info pages installed
# on the system. If the /usr/share/info/dir file ever
# needs to be recreated, the following optional commands
# will accomplish the task:
pushd /usr/share/info
rm -v dir
for f in *
  do install-info $f dir 2>/dev/null
done
popd