#!/bin/bash

FOLDERNAME="util-linux-2.27"
FILENAME="util-linux-2.27.tar.xz"

# The Util-linux package contains miscellaneous utility programs.
# Among them are utilities for handling file systems, consoles,
# partitions, and messages.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# The FHS recommends using the /var/lib/hwclock directory instead
# of the usual /etc directory as the location for the adjtime file.
# First create a directory to enable storage for the hwclock program
mkdir -pv /var/lib/hwclock

# Prepare Util-Linux for compilation:
./configure ADJTIME_PATH=/var/lib/hwclock/adjtime     \
            --docdir=/usr/share/doc/util-linux-2.27 \
            --disable-chfn-chsh  \
            --disable-login      \
            --disable-nologin    \
            --disable-su         \
            --disable-setpriv    \
            --disable-runuser    \
            --disable-pylibmount \
            --disable-static     \
            --without-python
            
# Compile the package
make

# Install the package
make install