#!/bin/bash

FOLDERNAME="xz-5.2.1"
FILENAME="xz-5.2.1.tar.xz"

# The Xz package contains programs for compressing and
# decompressing files. It provides capabilities for the
# lzma and the newer xz compression formats. Compressing
# text files with xz yields a better compression percentage
# than with the traditional gzip or bzip2 commands.
    
# Change directory
cd /src/pkg/basic/${FOLDERNAME}

# Prepare Xz for compilation
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xz-5.2.1

# Compile the package
make

# Install the package
make install

# Make sure all the essential files are in the right directory
mv -v   /usr/bin/{lzma,unlzma,lzcat,xz,unxz,xzcat} /bin
mv -v /usr/lib/liblzma.so.* /lib
ln -svf ../../../../lib/$(readlink /usr/lib/liblzma.so) /usr/lib/liblzma.so