#!/bin/bash

FOLDERNAME="expect5.45"
FILENAME="expect5.45.tar.gz"

# Force Expect's configure script to use /bin/stty instead 
# of a /usr/local/bin/stty it may find on the host system.
# This will ensure that our test suite tools remain sane 
# for the final builds of our toolchain.
cp -v ../../pkg/${FOLDERNAME}/configure{,.orig}
sed 's:/usr/local/bin:/bin:' ../../pkg/${FOLDERNAME}/configure.orig > ../../pkg/${FOLDERNAME}/configure

# Prepare Expect for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools       \
            --with-tcl=/tools/lib                       \
            --with-tclinclude=/tools/include
            
# Build the package
make $MAKEFLAGS

# Run the Expect test suite
make $MAKEFLAGS test

# Install the package
make $MAKEFLAGS SCRIPTS="" install