#!/bin/bash

FOLDERNAME="file-5.24"
FILENAME="file-5.24.tar.gz"

# Prepare File for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools

# Build the package
make $MAKEFLAGS

# Run the File test suite
make $MAKEFLAGS check

# Install the package
make $MAKEFLAGS install