#!/bin/bash

FOLDERNAME="file-5.24"
FILENAME="file-5.24.tar.gz"

# The File package contains a utility for determining
# the type of a given file or files.

cd ../../pkg/basic/${FOLDERNAME}

# Prepare File for compilation
./configure --prefix=/tools

# Compile the package
make $MAKEFLAGS

# Install the package
make $MAKEFLAGS install