#!/bin/bash

FOLDERNAME="findutils-4.4.2"
FILENAME="findutils-4.4.2.tar.gz"

# The Findutils package contains programs to find files.
# These programs are provided to recursively search through
# a directory tree and to create, maintain, and search a
# database (often faster than the recursive find, but
# unreliable if the database has not been recently updated).

cd ../../pkg/basic/${FOLDERNAME}

# Prepare Findutils for compilation
./configure --prefix=/tools

# Compile the package
make $MAKEFLAGS

# Install the package
make $MAKEFLAGS install