#!/bin/bash

FOLDERNAME="findutils-4.4.2"
FILENAME="findutils-4.4.2.tar.gz"

# Prepare Find-Utils for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools

# Build the package
make $MAKEFLAGS

# Run the Find-Utils test suite
make $MAKEFLAGS check

# Install the package
make $MAKEFLAGS install