#!/bin/bash

FOLDERNAME="gawk-4.1.3"
FILENAME="gawk-4.1.3.tar.xz"

# Prepare Gawk for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools

# Build the package
make $MAKEFLAGS

# Run the Gawk test suite
make $MAKEFLAGS check

# Install the package
make $MAKEFLAGS install