#!/bin/bash

FOLDERNAME="gawk-4.1.3"
FILENAME="gawk-4.1.3.tar.xz"

# The Gawk package contains programs for manipulating
# text files.

cd ../../pkg/basic/${FOLDERNAME}

# Prepare Gawk for compilation
./configure --prefix=/tools

# Compile the package
make $MAKEFLAGS

# Install the package
make $MAKEFLAGS install