#!/bin/bash

FOLDERNAME="gcc-5.2.0"
FILENAME="gcc-5.2.0.tar.bz2"

pass1() {
    displayMsg OK "Building Pass 1 ..."
    
    # GCC now requires the GMP, MPFR and MPC packages. As these packages
    # may not be included in your host distribution, they will be built
    # with GCC. Unpack each package into the GCC source directory and
    # rename the resulting directories so the GCC build procedures will
    # automatically use them
    tar xf ../../pkg/basic/gmp-6.0.0a.tar.xz -C ../../pkg/basic
    tar xf ../../pkg/basic/mpc-1.0.3.tar.gz -C ../../pkg/basic
    tar xf ../../pkg/basic/mpfr-3.1.3.tar.xz -C ../../pkg/basic
    mv ../../pkg/basic/gmp-6.0.0 ../../pkg/basic/${FOLDERNAME}/gmp
    mv ../../pkg/basic/mpc-1.0.3 ../../pkg/basic/${FOLDERNAME}/mpc
    mv ../../pkg/basic/mpfr-3.1.3 ../../pkg/basic/${FOLDERNAME}/mpfr
    
    # Change the location of GCC's default dynamic linker to use the
    # one installed in /tools. It also removes /usr/include from GCC's
    # include search path.
    for file in \
        $(find ../../pkg/basic/${FOLDERNAME}/gcc/config -name linux64.h -o -name linux.h -o -name sysv4.h)
    do
        cp -u $file{,.orig}
        sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
            -e 's@/usr@/tools@g' $file.orig > $file
        echo '
#undef STANDARD_STARTFILE_PREFIX_1
#undef STANDARD_STARTFILE_PREFIX_2
#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
        touch $file.orig
    done
    
    # Prepare GCC for compilation
    ../../pkg/basic/${FOLDERNAME}/configure        \
    --target=$TARGET                               \
    --prefix=/tools                                \
    --with-glibc-version=2.11                      \
    --with-sysroot=$MOUNT_POINT                    \
    --with-newlib                                  \
    --without-headers                              \
    --with-local-prefix=/tools                     \
    --with-native-system-header-dir=/tools/include \
    --disable-nls                                  \
    --disable-shared                               \
    --disable-multilib                             \
    --disable-decimal-float                        \
    --disable-threads                              \
    --disable-libatomic                            \
    --disable-libgomp                              \
    --disable-libquadmath                          \
    --disable-libssp                               \
    --disable-libvtv                               \
    --disable-libstdcxx                            \
    --enable-languages=c,c++
    
    # Compile GCC
    make $MAKEFLAGS
    
    # Instale the package
    make $MAKEFLAGS install
    
    GCC_PASS1="true"
}

pass2() {
    displayMsg OK "Building Pass 2 ..."
}

if [ $GCC_PASS1 == "true" ]
then
    pass2
else
    pass1
fi