#!/bin/bash

FOLDERNAME="gcc-5.2.0"
FILENAME="gcc-5.2.0.tar.bz2"

# MPRF, MPC and GMP have already  been added to the tar

# Changes the location of GCC's default dynamic linker to use the one installed in 
# TOOLS_DIR. It also removes /usr/include from GCC's include search path.
for file in \
    $(find ../../pkg/${FOLDERNAME}/gcc/config -name linux64.h -o -name linux.h -o -name sysv4.h)
do
    cp -uv $file{,.orig}
    sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
        -e 's@/usr@/tools@g' $file.orig > $file
    echo '
    #undef STANDARD_STARTFILE_PREFIX_1
    #undef STANDARD_STARTFILE_PREFIX_2
    #define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
    #define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
    touch $file.orig
done

../../pkg/${FOLDERNAME}/configure                           \
    --target=${TARGET}                                      \
    --prefix=/tools                                         \
    --with-glibc-version=2.11                               \
    --with-sysroot=${MOUNT_POINT}                           \
    --with-newlib                                           \
    --without-headers                                       \
    --with-local-prefix=/tools                              \
    --with-native-system-header-dir=/tools/include          \
    --disable-nls                                           \
    --disable-shared                                        \
    --disable-multilib                                      \
    --disable-decimal-float                                 \
    --disable-threads                                       \
    --disable-libatomic                                     \
    --disable-libgomp                                       \
    --disable-libquadmath                                   \
    --disable-libssp                                        \
    --disable-libvtv                                        \
    --disable-libstdcxx                                     \
    --enable-languages=c,c++
    
make $MAKEFLAGS
make $MAKEFLAGS install