#!/bin/bash

FOLDERNAME="gettext-0.19.5.1"
FILENAME="gettext-0.19.5.1.tar.xz"

# Prepare Gettext for compilation
EMACS="no" ../../pkg/${FOLDERNAME}/gettext-tools/configure --prefix=/tools --disable-shared

# Build the package
make $MAKEFLAGS -C gnulib-lib
make $MAKEFLAGS -C intl pluralx.c
make $MAKEFLAGS -C src msgfmt
make $MAKEFLAGS -C src msgmerge
make $MAKEFLAGS -C src xgettext

# Install the msgfmt, msgmerge and xgettext programs
cp src/{msgfmt,msgmerge,xgettext} /tools/bin