#!/bin/bash

FOLDERNAME="gettext-0.19.5.1"
FILENAME="gettext-0.19.5.1.tar.xz"

# The Gettext package contains utilities for
# internationalization and localization. These allow
# programs to be compiled with NLS (Native Language
# Support), enabling them to output messages in the
# user's native language.

cd ../../pkg/basic/${FOLDERNAME}

# Prepare Gettext for compilation
cd gettext-tools
EMACS="no" ./configure --prefix=/tools --disable-shared

# Compile the package
make $MAKEFLAGS -C gnulib-lib
make $MAKEFLAGS -C intl pluralx.c
make $MAKEFLAGS -C src msgfmt
make $MAKEFLAGS -C src msgmerge
make $MAKEFLAGS -C src xgettext

# Install the msgfmt, msgmerge and xgettext programs
cp src/{msgfmt,msgmerge,xgettext} /tools/bin
