#!/bin/bash

FOLDERNAME="glibc-2.22"
FILENAME="glibc-2.22.tar.xz"

cd ../../pkg/${FOLDERNAME}

patch -Np1 -i ../glibc-2.22-upstream_i386_fix-1.patch

cd ../../build/glibc

../../pkg/${FOLDERNAME}/configure                             \
      --prefix=/tools                                         \
      --host=$TARGET                                          \
      --build=$(../../pkg/${FOLDERNAME}/scripts/config.guess) \
      --disable-profile                                       \
      --enable-kernel=2.6.32                                  \
      --enable-obsolete-rpc                                   \
      --with-headers=/tools/include                           \
      libc_cv_forced_unwind=yes                               \
      libc_cv_ctors_header=yes                                \
      libc_cv_c_cleanup=yes
      
make && make install

# Test the basic functions (compiling and linking) of the new toolchain are working as expected
echo 'int main(){}' > dummy.c
$TARGET-gcc dummy.c
readelf -l a.out | grep ': /tools'
if [ $? != 0 ]
then
    displayMsg ERR "Error code $?: Glibc Test failed!"
    exit 1
fi
rm dummy.c a.out