#!/bin/bash

FOLDERNAME="grep-2.21"
FILENAME="grep-2.21.tar.xz"

# Prepare Grep for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools

# Build the package
make $MAKEFLAGS

# Run the test suite
make $MAKEFLAGS check

# Install the package
make $MAKEFLAGS install