#!/bin/bash

FOLDERNAME="gzip-1.6"
FILENAME="gzip-1.6.tar.xz"

# Prepare Gzip for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools

# Build the package
make $MAKEFLAGS

# Run the test suite
make $MAKEFLAGS check

# Install the package
make $MAKEFLAGS install