#!/bin/bash

FOLDERNAME="gcc-5.2.0"
FILENAME="gcc-5.2.0.tar.bz2"

# Libstdc++ is the standard C++ library. It is needed for the
# correct operation of the g++ compiler.

# Prepare Libstdc++ for compilation
../../pkg/basic/${FOLDERNAME}/libstdc++-v3/configure   \
    --host=$TARGET                               \
    --prefix=/tools                              \
    --disable-multilib                           \
    --disable-nls                                \
    --disable-libstdcxx-threads                  \
    --disable-libstdcxx-pch                      \
    --with-gxx-include-dir=/tools/$TARGET/include/c++/5.2.0
    
# Compile libstdc++
make $MAKEFLAGS

# Install the library
make $MAKEFLAGS install