#!/bin/bash

FOLDERNAME="linux-4.2"
FILENAME="linux-4.2.tar.xz"

cp -rf ../../pkg/${FOLDERNAME}/* ./

# Make sure no stale files are embedded in the package
make mrproper

make INSTALL_HDR_PATH=dest headers_install
cp -rv dest/include/* /tools/include

