#!/bin/bash

FOLDERNAME="linux-4.2"
FILENAME="linux-4.2.tar.xz"

cp -rf ../../pkg/${FOLDERNAME}/* ./

# Make sure no stale files are embedded in the package
make $MAKEFLAGS mrproper

make $MAKEFLAGS INSTALL_HDR_PATH=dest headers_install
find dest/include \( -name .install -o -name ..install.cmd \) -delete
cp -r dest/include/* /usr/include