#!/bin/bash

FOLDERNAME="m4-1.4.17"
FILENAME="m4-1.4.17.tar.xz"

# The M4 package contains a macro processor.

cd ../../pkg/basic/${FOLDERNAME}

# Prepare M4 for compilation
./configure --prefix=/tools

# Compile the package
make $MAKEFLAGS

# Install the package
make $MAKEFLAGS install