#!/bin/bash

FOLDERNAME="make-4.1"
FILENAME="make-4.1.tar.bz2"

# Prepare Make for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools --without-guile

# Build the package
make $MAKEFLAGS

# Run the test suite
make $MAKEFLAGS check

# Install the package
make $MAKEFLAGS install