#!/bin/bash

FOLDERNAME="ncurses-6.0"
FILENAME="ncurses-6.0.tar.gz"

# Ensure that gawk is found first during configuration
sed -i s/mawk// ../../pkg/${FOLDERNAME}/configure

# Prepare NCurses for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools   \
            --with-shared                           \
            --without-debug                         \
            --without-ada                           \
            --enable-widec                          \
            --enable-overwrite

# Build the package
make $MAKEFLAGS

# Install the package
make $MAKEFLAGS install