#!/bin/bash

FOLDERNAME="patch-2.7.5"
FILENAME="patch-2.7.5.tar.xz"

# Prepare Patch for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools

# Build the package
make $MAKEFLAGS

# Run the test suite
make $MAKEFLAGS check

# Install the package
make $MAKEFLAGS install