#!/bin/bash

FOLDERNAME="perl-5.22.0"
FILENAME="perl-5.22.0.tar.xz"

cd ../../pkg/${FOLDERNAME}
# Prepare Perl for compilation
sh Configure -des -Dprefix=/tools -Dlibs=-lm

# Build the package
make $MAKEFLAGS

# Only a few of the utilities and libraries need to be
# installed at this time
cp -v perl cpan/podlators/pod2man /tools/bin
mkdir -pv /tools/lib/perl5/5.22.0
cp -Rv lib/* /tools/lib/perl5/5.22.0