#!/bin/bash

FOLDERNAME="texinfo-6.0"
FILENAME="texinfo-6.0.tar.xz"

# Prepare Texinfo for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools

# Build the package
make $MAKEFLAGS

# Run the test suite
make $MAKEFLAGS check

# Install the package
make $MAKEFLAGS install