#!/bin/bash

FOLDERNAME="util-linux-2.27"
FILENAME="util-linux-2.27.tar.xz"

# Prepare Util-Linux for compilation
../../pkg/${FOLDERNAME}/configure --prefix=/tools   \
            --without-python                        \
            --disable-makeinstall-chown             \
            --without-systemdsystemunitdir          \
            PKG_CONFIG=""

# Build the package
make $MAKEFLAGS

# Install the package
make $MAKEFLAGS install