#!/bin/bash

FOLDERNAME="xz-5.2.1"
FILENAME="xz-5.2.1.tar.xz"

# The Xz package contains programs for compressing and
# decompressing files. It provides capabilities for the
# lzma and the newer xz compression formats. Compressing
# text files with xz yields a better compression percentage
# than with the traditional gzip or bzip2 commands.

cd ../../pkg/basic/${FOLDERNAME}

# Prepare Xz for compilation
./configure --prefix=/tools

# Compile the package
make $MAKEFLAGS

# Install the package
make $MAKEFLAGS install